version: '3.9'

services:
  app:
    build:
      context: give-and-collect
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      CYPRESS_EMAIL: ${CYPRESS_EMAIL}
      CYPRESS_PASSWORD: ${CYPRESS_PASSWORD}
    volumes:
      - .:/app

  cypress:
    image: cypress/included:12.12.0
    depends_on:
      - app
    environment:
      CYPRESS_BASE_URL: http://app:3000
      CYPRESS_EMAIL: ${CYPRESS_EMAIL}
      CYPRESS_PASSWORD: ${CYPRESS_PASSWORD}
    entrypoint: [ "npx", "cypress", "run" ]