on:
  pull_request:
    branches:
      - main

jobs:
  # Définir le job de build Docker
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.ACTOR }}
          password: ${{ secrets.TOKEN }}

      - name: Build docker image with ghcr
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ vars.ACTOR }}/test-cicd:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            CYPRESS_EMAIL=${{ secrets.CYPRESS_EMAIL }}
            CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to the server via SSH"
            sudo docker login ghcr.io -u ${{ vars.ACTOR }} -p ${{ secrets.TOKEN }}
            sudo docker stop $(docker ps -q) && docker rm $(docker ps -a -q)
            sudo docker stop test-cicd:latest || true
            sudo docker rmi $(docker images -a -q)
            sudo docker rm test-cicd:latest || true
            sudo docker pull ghcr.io/${{ vars.ACTOR }}/test-cicd:latest
            sudo docker run -d --name test-cicd -p 80:3000 ghcr.io/${{ vars.ACTOR }}/test-cicd:latest
            sudo docker-compose up -d
