on:
  pull_request:
    branches:
      - main

jobs:
  # Définir le job de build Docker
#  docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ vars.ACTOR }}
#          password: ${{ secrets.TOKEN }}
#
#      - name: Build docker image with ghcr
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          tags: ghcr.io/${{ vars.ACTOR }}/giveandcollect:latest
#          build-args: |
#            DATABASE_URL=${{ secrets.DATABASE_URL }}
#            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
#            EMAIL_USER=${{ secrets.EMAIL_USER }}
#            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
#            CYPRESS_EMAIL=${{ secrets.CYPRESS_EMAIL }}
#            CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }}

  deploy:
#    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name:
        run: ls
      - name:
        run: pwd
      - name: Copy Docker Compose file to server
        run: scp -o StrictHostKeyChecking=no ./docker-compose.yml ubuntu@${{ vars.SSH_HOST }}:/home/ubuntu/docker-compose.yml


      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to the server via SSH"
            cd /home/ubuntu/
            ls
            sudo docker login ghcr.io -u ${{ vars.ACTOR }} -p ${{ secrets.TOKEN }}
            sudo docker stop giveandcollect || true
            sudo docker rm giveandcollect || true
            sudo docker pull ghcr.io/${{ vars.ACTOR }}/giveandcollect:latest
            ls
            pwd
            docker-compose up -d
